name: typeset
version: "1.1"
license: "GPL-2.0-or-later"
date: 2022-12-05
description: |
    Automatic typesetting framework for common GAP objects, with LaTeX generation

authors:
    - name: Zachariah Newbery
      url: https://zachnewbery.com

maintainers:
    - name: Zachariah Newbery
      url: https://zachnewbery.com

GAP: ">= 4.11"

suggested-pkgs:
    - name: "digraphs"
      version: ">=1.5.0"
      url: "https://digraphs.github.io/Digraphs"

www: https://ZachNewbery.github.io/typeset/
readme: README.md
packageinfo: https://ZachNewbery.github.io/typeset/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/ZachNewbery/typeset/releases/download/v1.1/typeset-1.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    latex, typesetting, markdown.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>New22</span>]   <b class='BibAuthor'>Newbery, Z.</b>,
     <i class='BibTitle'>typeset, Automatic typesetting framework for common GAP objects, with LaTeX generation,
             Version 1.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://ZachNewbery.github.io/typeset/">https://ZachNewbery.github.io/typeset/</a></span>.
    </p>
    

bibtex: |
    @misc{ typeset1.1,
      author =           {Newbery, Z.},
      title =            {{typeset},  Automatic typesetting framework for common
                          GAP objects, with LaTeX generation, {V}ersion 1.1},
      month =            {Dec},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href         {https://ZachNewbery.github.io/typeset/}
                          {\texttt{https://ZachNewbery.github.io/}\discretionary
                          {}{}{}\texttt{typeset/}}},
      keywords =         {latex; typesetting; markdown},
      printedkey =       {New22}
    }

