name: typeset
version: "1.2.1"
license: "GPL-2.0-or-later"
date: 2024-02-20
description: |
    Automatic typesetting framework for common GAP objects, with LaTeX generation

authors:
    - name: Zachariah Newbery
      url: https://zachnewbery.com

maintainers:
    - name: Zachariah Newbery
      url: https://zachnewbery.com

GAP: ">= 4.11"

suggested-pkgs:
    - name: "digraphs"
      version: ">=1.5.0"
      url: "https://digraphs.github.io/Digraphs"

www: https://gap-packages.github.io/typeset/
readme: README.md
packageinfo: https://gap-packages.github.io/typeset/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/typeset/releases/download/v1.2.1/typeset-1.2.1.tar.gz

abstract: |

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    latex, typesetting, markdown.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>New24</span>]   <b class='BibAuthor'>Newbery, Z.</b>,
     <i class='BibTitle'>typeset, Automatic typesetting framework for common GAP objects, with LaTeX generation,
             Version 1.2.1</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/typeset/">https://gap-packages.github.io/typeset/</a></span>.
    </p>
    

bibtex: |
    @misc{ typeset1.2.1,
      author =           {Newbery, Z.},
      title =            {{typeset},  Automatic typesetting framework for common
                          GAP objects, with LaTeX generation, {V}ersion 1.2.1},
      month =            {Feb},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/typeset/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{typeset/}}},
      keywords =         {latex; typesetting; markdown},
      printedkey =       {New24}
    }

