name: latexgen
version: "0.99"
license: "GPL-2.0-or-later"
date: 2022-11-11
description: |
    Automatic LaTeX string generation for common GAP objects

authors:
    - name: Zachariah Newbery
      url: https://zachnewbery.com

maintainers:
    - name: Zachariah Newbery
      url: https://zachnewbery.com

GAP: ">= 4.11"

www: https://ZachNewbery.github.io/latexgen/
readme: README.md
packageinfo: https://ZachNewbery.github.io/latexgen/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/ZachNewbery/latexgen/releases/download/v0.99/latexgen-0.99.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    latex, typesetting, markdown.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>New22</span>]   <b class='BibAuthor'>Newbery, Z.</b>,
     <i class='BibTitle'>latexgen, Automatic LaTeX string generation for common GAP objects,
             Version 0.99</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://ZachNewbery.github.io/latexgen/">https://ZachNewbery.github.io/latexgen/</a></span>.
    </p>
    

bibtex: |
    @misc{ latexgen0.99,
      author =           {Newbery, Z.},
      title =            {{latexgen},  Automatic  LaTeX  string  generation  for
                          common GAP objects, {V}ersion 0.99},
      month =            {Nov},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href        {https://ZachNewbery.github.io/latexgen/}
                          {\texttt{https://ZachNewbery.github.io/}\discretionary
                          {}{}{}\texttt{latexgen/}}},
      keywords =         {latex; typesetting; markdown},
      printedkey =       {New22}
    }

