name: CI

# Trigger the workflow on push to master / main, or on pull request
on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.11
        pkgs-to-clone: 
          - datastructures NautyTracesInterface digraphs

    steps:
      - name: "Checkout package repository"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v1
      - name: "Install dot2tex dependencies"
        run: sudo apt install graphviz texlive preview-latex-style
      - name: "Install dot2tex with pip"
        run: pip install dot2tex
      - name: "Setup GAP"
        uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_CLONE: "${{ matrix.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "io orb profiling grape NautyTracesInterface datastructures digraphs"
          GAPBRANCH: ${{ matrix.gap-branch }}
      - name: "Build 'typeset' package"
        uses: gap-actions/build-pkg@v1
      - name: "Run 'typeset' package tests"
        uses: gap-actions/run-pkg-tests@v2
      - name: "Process test coverage"
        uses: gap-actions/process-coverage@v2
      - name: "Publish code coverage"
        uses: codecov/codecov-action@v2

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf
